spring:
  application:
    name: veri-rag
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://llm-1yauwtsqkmv66e2w.cn-beijing.maas.aliyuncs.com/compatible-mode/v1
      chat:
        model: qwen3.7-plus
      embedding:
        model: qwen3.7-text-embedding
        dimensions: 1024
    vectorstore:
      redis:
        initialize-schema: true
        index-name: veri-rag-index
        prefix: "veri-rag:embedding:"
  data:
    redis:
      url: redis://localhost:6380
      client-type: jedis
  datasource:
    url: jdbc:mysql://localhost:3306/db_java1234_rag?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8081
  servlet:
    context-path: /veri-rag

file:
  upload:
    path: ./file

logging:
  file:
    path: ${LOG_PATH:logs}
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    com.example.verirag: ${APP_LOG_LEVEL:DEBUG}
    org.springframework.ai: DEBUG
    org.mybatis: DEBUG
mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

jwt:
  secret: VYdac/JBAW+noUscEgYffr/TlUgPwCHZkFkULziZ8kTZOb6sF6ylZYgXj4XisLr4
  expire-hours: 24
